### ISSUE TITLE
Couldn't install on current version of VSCode

### ISSUE THREAD

**Issue by RomanGrankin** [pepri/subtitles-editor#1]
Не удалось установить расширение 'pepri.subtitles-editor-0.0.1', так как оно не совместимо с Code '1.24.1'.

And also, do you need any help with your extension?

**Comment by pepri** [comment]
This extension uses vscode 1.25 (see ‘package.json‘). You should be able to install it after updating your VS code.

You can create an issue or submit a PR, if you are missing any feature. Maybe add support for other formats of subtitles like ‘.sub‘ for instance.
