### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by macgile** [pepri/subtitles-editor#12]
Hi all,

Thank you for this tool which is of great use.

When translating there is a gap between the translated text and the temp line, the text goes above the temp line.
Below is an extract from an English subtitle file translated into French.

****************************
original in english
****************************
286
00:10:55,360 --> 00:10:57,640
the output of that uniform color node

287
00:10:57,640 --> 00:11:00,100
and connect it here to the metallic when

288
00:11:00,100 --> 00:11:02,050
I let go the mouse you can see here that

289
00:11:02,050 --> 00:11:05,059
the viewport updates now

290
00:11:05,059 --> 00:11:08,779
we have a very shiny metallic surface so

291
00:11:08,779 --> 00:11:10,699
what we want to do now is add some

**************************************
after the translation into French
**************************************
286
00:10:55,360 --> 00:10:57,640
la sortie de ce nœud de couleur uniforme

287
00:10:57,640 --> 00:11:00,100
et connectez-le ici au métallique lorsque
288
J'ai lâché la souris, tu peux voir ici que
00:11:00,100 --> 00:11:02,050

289
la fenêtre est mise à jour maintenant
00:11:02,050 --> 00:11:05,059

290
nous avons une surface métallique très brillante donc
00:11:05,059 --> 00:11:08,779

291
ce que nous voulons faire maintenant, c'est en ajouter
00:11:08,779 --> 00:11:10,699

**************************

this inversion continues until the end of the file.

**Comment by pepri** [comment]
Hi, can you provide the complete file so I can reproduce this issue? Trying with just this snippet does not trigger it.

**Comment by pepri** [comment]
I updated the translation to skip empty lines which could cause this issue. Fix is in 1.1.5. If you still experience the issue with the latest version, please provide a complete file I can use to reproduce it.
