### ISSUE TITLE
[feature] shit the sequences

### ISSUE THREAD

**Issue by hawkchen** [pepri/subtitles-editor#2]
If I need to insert a new subtitle among existing ones, I have to shift all sequences behind the inserted sequence.

If there is a "shift sequences" (like shift time) which can shift all sequences for me, it would be more helpful.
e.g. insert one subtitle between 1 and 2, so I have to shift sequences like:
2 -> 3
3 -> 4
4 -> 5
...

**Comment by pepri** [comment]
I have added an option to renumber sequences: 953d0bb99ebf9e4a2cc669467db889b17eb11899

So for this case, just insert any new subtitles, choose **Subtitles: Renumber**, confirm start of the sequence to be 1 and it will renumber all the frames using the given start index.
