### ISSUE TITLE
Ability to sort subtitles basd on timestamps

### ISSUE THREAD

**Issue by Fortis-one** [pepri/subtitles-editor#20]
Could be useful in merging 2 sub files like forced track and default track. Something like [this](https://gist.github.com/GChristensen/928115#file-srt-sort-py).

**Comment by pepri** [comment]
The feature to sort the frames by timestamp was added in 1.1.7 as "Subtitles: Reorder by Timestamp" command. The original "Subtitles: Reorder" was renamed to "Subtitles: Reorder by Sequence". Thanks!
