### ISSUE TITLE
Leave the original sentence when srt translation

### ISSUE THREAD

**Issue by kevinknox936** [pepri/subtitles-editor#4]
Dear Peter Prikryl:
Thank you in advance. I really love this vs code extension. It helps me a lot in srt translation. But I wonder whether it have or can be added an option, i.e., at present , it delete original sentence then paste translated sentence. An desired Option is: add an option on the fly to choose to leave original sentence or not, and then add translated sentence below it so that I can check it line by line.
Sorry about my pool English, hope you can understand what I mean. Anyway, Thank you very much.

**Comment by pepri** [comment]
Hi Kevin,

I have just added a feature to reorder subtitles based on their sequence number that can help you translating subtitles. If you first translate the subtitles and then append the original subtitles at the end, you can reorder them using this new command. After this, the translated frame will be followed by the one in the original language.

I hope this helps,
Peter
