### ISSUE TITLE
Subtitles: Translate 

### ISSUE THREAD

**Issue by acamposxp** [pepri/subtitles-editor#5]
I could not quite understand how the translation works. The subtitle is in English and I would like to translate it into Portuguese. But I use the command "Subtitles: Translate" and the text continues in English. What do I have to do additionally?

**Comment by pepri** [comment]
After choosing the language, it will do translate the subtitles. It can take few seconds to do so. If it is still not working for you, please attach a `.srt` file so I can test it with it. I have checked now with some other file and translation to Portuguese worked for me.

**Comment by andreamussap** [comment]
Hi, @pepri 
I ran Subtitles: Translate and got command not found!? Can you help?

```
(base) my-MacBook-Pro:~ andreamussap$ Subtitles: Translate
bash: Subtitles:: command not found
```

**Comment by pepri** [comment]
This is not a command you can use in the shell. This is an extension to Visual Studio Code editor. You can execute the command from Visual Studio Code editor.
