### ISSUE TITLE
Comma vs Period in timestamps

### ISSUE THREAD

**Issue by wesbos** [pepri/subtitles-editor#7]
Thanks a ton for this! Exactly what I needed to shift my timestamps.

One thing I ran into it that my .vtt subtitles are like this:

`00:00:01.863 --> 00:00:02.730`

and when I shift it goes to commas:

`00:00:01,863 --> 00:00:02,730`

Any way to specify this? It breaks the track on websites for me

**Comment by wesbos** [comment]
Oh is this because this extension is meant to SRT and not VTT? It worked anyways. Not sure if that is the only difference.

**Comment by pepri** [comment]
I added support for WebVTT and SubViewer file formats. Thanks!
